require: 
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

  Exclude:
    - tmp/**/*
    - vendor/**/*
    - db/**/*
    - Guardfile
    - lib/tasks/cucumber.rake
    - project_secrets.rb

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Rails:
  Enabled: true

Rails/Blank:
  Enabled: true
  NotPresent: true
  NilOrEmpty: true
  UnlessPresent: false

Rails/Delegate:
  Enabled: false

Rails/FilePath:
  Enabled: false

Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Max: 15
  Exclude:
    - Vagrantfile

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - Rakefile
    - lib/tasks/**/*.rake
    - spec/**/*.rb
    - app/admin/**/*.rb

Metrics/AbcSize:
  Exclude:
    - Vagrantfile

Metrics/CyclomaticComplexity:
  Exclude:
    - Vagrantfile

Metrics/PerceivedComplexity:
  Exclude:
    - Vagrantfile

Rails/ApplicationRecord:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*.rb
    - /**/*_spec.rb

Style/AndOr:
  EnforcedStyle: conditionals

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - Vagrantfile

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '{}'
    '%i': '{}'
    '%w': '{}'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
  
RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4
  
RSpec/NestedGroups:
  Max: 4
  
RSpec/ExampleLength:
  Max: 8

